# Generated by Django 6.0.6 on 2026-07-04 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('character', 'Character'), ('faction', 'Faction'), ('mechanic', 'Mechanic'), ('act', 'Act'), ('location', 'Location'), ('lore_topic', 'Lore Topic'), ('game_system', 'Game System'), ('class', 'Class')], max_length=20)),
                ('status', models.CharField(choices=[('corroborated', 'Corroborated'), ('uncorroborated', 'Uncorroborated')], default='uncorroborated', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('dialogue', 'Dialogue'), ('flavour_text', 'Flavour Text'), ('environmental', 'Environmental'), ('quest_text', 'Quest Text'), ('lore_object', 'Lore Object'), ('skill_gem_description', 'Skill Gem Description'), ('other', 'Other')], max_length=30)),
                ('game', models.CharField(choices=[('poe1', 'Path of Exile 1'), ('poe2', 'Path of Exile 2')], max_length=10)),
                ('patch_added', models.CharField(blank=True, max_length=20)),
                ('patch_removed', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('current', 'Current'), ('replaced', 'Replaced'), ('removed', 'Removed'), ('datamined', 'Datamined')], default='current', max_length=20)),
                ('context_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lore.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lore.entry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_tags', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='lore.entry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='lore.tag')),
            ],
            options={
                'unique_together': {('entry', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('target_type', models.CharField(choices=[('entry', 'Entry'), ('entry_tag', 'Entry Tag'), ('context_note', 'Context Note')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'target_type', 'target_id')},
            },
        ),
    ]
